# gray -> window3x3 -> sobel
delivery/CCIC_H6A_BOARD_DELIVERY_2026-04-19/B_external_stream_std_library/01_gray_window_filter_chain/rtl/gray_window_sobel_chain_top.v
delivery/CCIC_H6A_BOARD_DELIVERY_2026-04-19/C_shared_dependencies/rtl/grayscale_stream_std.v
delivery/CCIC_H6A_BOARD_DELIVERY_2026-04-19/C_shared_dependencies/rtl/window3x3_stream_std.v
delivery/CCIC_H6A_BOARD_DELIVERY_2026-04-19/B_external_stream_std_library/01_gray_window_filter_chain/rtl/sobel3x3_stream_std.v
